name: "4 en línea"

on:
#  issues:
#    types: [opened]

jobs:
  4-en-linea:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'bot|')

    env:
      BOT_PROMPT: ${{ github.event.issue.title }}
      GITHUB_TOKEN: ${{ github.token }}
      GIT_USER: ${{ github.repository_owner }}

    steps:
    - name: Instalando hub
      run: sudo snap install --classic hub

    - name: Checkout
      uses: actions/checkout@v2

    - name: Instalando Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'
    
    - name: Ejecutando el juego
      run: |
        FICHA=$(echo $BOT_PROMPT | cut -d "|" -f2)
        COLOR=$(echo $BOT_PROMPT | cut -d "|" -f3)
        python3 profile/4-en-linea/main.py $FICHA $COLOR
    
    - name: Guardando los cambios
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add --all
        git commit -am ":robot: Ficha $COLOR en columna $FICHA"
        git push
    
    - name: Cerrando el issue
      run: hub api -XPATCH repos/${{ github.repository }}/issues/${{ github.event.issue.number }} -f state=closed